### ISSUE TITLE
Wallstreet page

### ISSUE THREAD

**Issue by Neamar** [Neamar/corporate#120]
(all designs by @Licoti, posting here for safekeeping)

![corpov2](https://cloud.githubusercontent.com/assets/536844/7428864/3ad07254-eff8-11e4-9d25-a192001c63c6.jpg)

**Comment by Neamar** [comment]
![corporate-v3](https://cloud.githubusercontent.com/assets/536844/7428870/5132c6dc-eff8-11e4-8229-f76f8a0b1aa1.jpg)

**Comment by Neamar** [comment]
![corporate-v3 1](https://cloud.githubusercontent.com/assets/536844/7428871/56cfa2c2-eff8-11e4-86cc-ad9b4d5c89e4.jpg)

**Comment by Neamar** [comment]
![corporate-v4](https://cloud.githubusercontent.com/assets/536844/7428886/5dd840ec-eff8-11e4-91f6-048c922e88fd.jpg)

**Comment by julesduroux** [comment]
![corporate-v5](https://cloud.githubusercontent.com/assets/4954765/7428902/92a0e1d0-eff8-11e4-9716-f26bac75232f.jpg)

**Comment by your-mom-noob** [comment]
I believe the rank should pop out more. Black on black doesn't make it obvious enough that this is a ranking

**Comment by your-mom-noob** [comment]
Docking the markets inside an element wold be more appropriate visually

**Comment by Licoti** [comment]
![corporate-v3 1-wall1](https://cloud.githubusercontent.com/assets/539146/7441331/e7016d80-f0e3-11e4-8c76-6e7b59a64acd.jpg)

**Comment by julesduroux** [comment]
Hello,

Je poste un retour de ma copine : 

pour le triangle de classement elle trouve que c'est dommage d'avoir un triangle différent des autres.
Elle propose de passer de ça :
![image](https://cloud.githubusercontent.com/assets/4954765/7509552/6b272e04-f492-11e4-81cd-022a157d3f21.png)
à ça : 
![image](https://cloud.githubusercontent.com/assets/4954765/7509554/72734288-f492-11e4-9567-ebf7638ce5b1.png)


Qu'en pensez-vous ?

**Comment by Neamar** [comment]
C'est très bien... mais très compliqué à coder en CSS ;)

**Comment by Neamar** [comment]
Also see #95 for a first version (on peut en récupérer les images, et le less. Peut-être un bout de html aussi)

**Comment by julesduroux** [comment]
Voici mes retours suite à la permière version de Rudy : 
![image](https://cloud.githubusercontent.com/assets/4954765/11841131/57156da4-a3fb-11e5-930e-86bd09ac6cb6.png)

Je me lance même si je me doute que tout n'est pas fini. Par rapport à la maquette il manque encore ces points :
 - Il manque les valeurs numériques sur les marchés
 - tout est sur une seule colonne alors qu'il y en a deux sur la maquette

Je note quand même quelques petits trucs : 
 - Comme on peut le voir sur Shinsekai, le 5eme marché rentre en conflit avec le delta par rapport au tour précédent. Leur être qu'on peut remplacer ce carré par un triangle sur la ligne supérieure ? C'est à discuter.
 - La couleur de ce delta par rapport au tour précédent est rouge quand ça n'a pas bougé et verte quand ça a changé par rapport au tour précédent. Ca devait être rouge quand c'est pire que le tour d'avant, vert quand c'est mieux et noir ou gris quand ça n'a pas changé. Voir que ça ne s'affiche pas. La encore c'est à discuter.
 - Je ne suis pas fan du nom en rouge au survol de la corpo par le curseur pour indiquer qu'on peut cliquer. Mais je n'ai pas vraiment mieux  proposer. Et si ça ne choque personne d'autre ce n'est pas grave.

Quelques trucs en plus qui n'étaient pas identifiés : 
 - Il faudrait un effet visuel pour distinguer les corpos qui ont crashé ce tour-ci. Par exemple la corpo en rouge ou autre chose. A discuter.
 - Finalement il y a trois chiffres autour du nom de la corpo et ce n'est pas très intuitif de savoir lequel est quoi. Pourrait-on afficher des informations au survol du curseur ? Par exemple 'La corporation est 4eme au classement', 'la corporation a 14 actifs' ou 'Shensekaï a perdu 2 actifs depuis le tour précédent'

J'ai bien conscience que ce n'est pas à Rudy de gérer tous ces points. 
Les autres, votre avis ?

**Comment by julesduroux** [comment]
Done
