### ISSUE TITLE
Corporation detail page

### ISSUE THREAD

**Issue by Neamar** [Neamar/corporate#123]
Cette page s'affiche quand on clique sur une corpo depuis Wallstreet,

Une lightbox s'ouvre alors avec les informations suivantes, découpées par section :

* Nom de la corpo
* Logo
* Actifs
* Les détails pour chaque marché des actions qui l'ont affecté ce tour ci
* La liste des joueurs avec des parts dans cette corporation
* La liste des effets qui s'appliquent sur la corpo sans s'appliquer sur un marché en particulier
* Un tableau listant, pour chacun des marchés de la corporation, les autres corporations dans le même domaine, leur nombre d'actifs dans ce marché, leur nombre d'actifs au total et les joueurs dedans (cf. tableau ci dessous)
* Les effets premiers / derniers / crash et un lien vers la description de la corpo

|          | Agro | Construction | Spatial | Σ  | Joueurs             |
|----------|------|--------------|---------|----|---------------------|
| Enercore | 1    |              | 5       | 18 | Bom, Rudy, Matthieu |
| Iris     |      | 3            |         | 22 | Rudy, Jules         |

**Comment by Licoti** [comment]
![corporate-v3-detailcorpo](https://cloud.githubusercontent.com/assets/539146/7434731/6a3957b4-f03d-11e4-8c9e-59a3af81007d.jpg)

**Comment by Licoti** [comment]
![corporate-v3-detailcorpo](https://cloud.githubusercontent.com/assets/539146/7435178/9ef45360-f041-11e4-9666-815087c637f6.jpg)

**Comment by Licoti** [comment]
![corporate-v3-detailcorpo](https://cloud.githubusercontent.com/assets/539146/7435503/8a4d0d28-f044-11e4-8d17-74f777010469.jpg)

**Comment by Neamar** [comment]
Yay !

Ça semble pas mal du tout :)

Après réflexion il manque une dernière section, les informations liées à la corpo mais non liées à un marché (achat de part, prise de citoyenneté corpo)

On pourrait ajouter ça sous la forme d'une ligne d'icones en plus, après les joueurs (ou avant ?).

Ça prendrait le même format que les lignes d'icones dans le pod "Joueurs".

**Comment by Licoti** [comment]
![corporate-v3-detailcorpo](https://cloud.githubusercontent.com/assets/539146/7437594/01c75dc2-f059-11e4-90b4-12fe26d6a397.jpg)

**Comment by julesduroux** [comment]
Done
