### ISSUE TITLE
Players page

### ISSUE THREAD

**Issue by Neamar** [Neamar/corporate#124]
Page avec le tableau joueur / corporation, de ce genre :

![table-2](https://cloud.githubusercontent.com/assets/536844/7436946/e2e64874-f052-11e4-8a4d-636b6dcb3858.jpg)

**Comment by Licoti** [comment]
![corporate-v3 1-table](https://cloud.githubusercontent.com/assets/539146/7440823/95f12e52-f0cb-11e4-8208-9ccb2065e918.jpg)

**Comment by Licoti** [comment]
![corporate-v3 1-table](https://cloud.githubusercontent.com/assets/539146/7440843/97fde13a-f0cc-11e4-940a-a050b883e489.jpg)
