### ISSUE TITLE
Icons list

### ISSUE THREAD

**Issue by Neamar** [Neamar/corporate#127]
On va avoir besoin des icones suivantes :

Avec effets sur les actifs :

- [x] Voix au chapitre positives
- [x] Voix au chapitre négatives
- [x] Effets premier
- [x] Effets dernier
- [x] Effet crash
- [x] Sabotage
- [x] Datasteal positif
- [x] Datasteal négatif (affiché uniquement dans le détail d'une corpo) 
- [x] Protection (affiché uniquement dans le détail d'une corpo) 
- [x] Extraction positive
- [x] Extraction négative
- [x] DInc: Développement urbain positif
- [x] DInc: Développement urbain négatif
- [x] Main du marché positive
- [x] Main du marché négative
- [ ] Le marché a gagné un actif de domination
- [ ] Le marché a perdu un actif de domination
- [ ] Le marché est en perte sèche
- [ ] Le marché se remet de sa perte sèche
- [x] "Inconnu" (les "???")

Sans effets sur les actifs :
- [x] Ajout de nationalité corpo
- [x] Perte de nationalité corpo
- [x] Lancement d'une run de sabotage (reprendre l'icone du sabotage)
- [x] Lancement d'une run de protection
- [x] Lancement d'une run de datasteal (reprendre l'icone du datasteal)
- [x] Lancer une run d'extraction (reprendre l'icone de l'extraction)
- [x] Augmentation de l'IC
- [x] Lancement d'une run d'information
- [ ] DInc : bonus de consolidation
- [ ] DInc : malus de consolidation
- [ ] DInc : bonus de la réforme de sécurité
- [ ] DInc : malus de la réforme de sécurité
- [x] Résultat de spéculation
- [x] Wiretransfer
- [x] Achat de part
- [ ] Vote DInc : consolidation
- [ ] Vote DInc : réforme sécurité
- [ ] Vote DInc : développement urbain
- [x] Argent de début de tour suivant
- [x] Background du joueur

Marchés :

- [x] Agroalimentaire
- [x] Aérospatiale
- [x] BTP
- [x] Militaire
- [x] Médias
- [x] Pharmaceutique
- [x] Robotique
- [x] Transport
- [x] Télécom
- [x] Énergie

Les trois lignes du DInc :

- [x] Contrat public
- [x] Réforme de la sécurité
- [x] Consolidation
- [x] Aucun vote

Général :

- [x] Icône pour les règles (le petit livre)

**Comment by julesduroux** [comment]
J'ai ajouté les gain/perte d'actif de perte sèche et de domination.
J'ai aussi ajouté la distinction entre gagner la citoyenneté corporatiste et la perdre.

**Comment by Licoti** [comment]
J'ajoute les icones, au fur et à mesure, n'hésitez pas à donner votre avis.

Achat d'une part, Protection, Speculation, Vote négatif / positif
![achat-part](https://cloud.githubusercontent.com/assets/539146/7572974/8f752296-f822-11e4-957a-bc198fae7b15.png)
![protection](https://cloud.githubusercontent.com/assets/539146/7572973/8f73fd6c-f822-11e4-816e-06c91c8c9a44.png)
![speculer](https://cloud.githubusercontent.com/assets/539146/7572975/8f77997c-f822-11e4-826a-45a78618d93a.png)
![vote-negatif](https://cloud.githubusercontent.com/assets/539146/7572976/8f7815e6-f822-11e4-90fd-cfa3b81e4fe7.png)
![vote-positif](https://cloud.githubusercontent.com/assets/539146/7572977/8f7ac53e-f822-11e4-8b49-b84828bf364b.png)

**Comment by Neamar** [comment]
@Licoti j'ai mis à jour ton commentaire pour en faire un tableau ça nous facilitera la vie pour en ajouter plus derrière, je te laisse regarder la structure

**Comment by Neamar** [comment]
Et sinon pour répondre à la question posée @Licoti moi j'aime bien ces 5 premiers :)

**Comment by Neamar** [comment]
@Licoti on peut faire du niveau de gris dans une police d'icone ? Je pensais qu'on était limités au monochrome.

**Comment by Licoti** [comment]
Yes, bien vu, j'ai re-fais les polices en noir et blanc

**Comment by Neamar** [comment]
Hey @Licoti ! Ça me plaît toujours bien.

Pour les positifs négatifs, il est possible d'avoir de la couleur quand même, faut juste que ce soit uni. Tu dirais quoi d'avoir la même icone en rouge ou vert ?

**Comment by Licoti** [comment]
Ok, du coup, j'enlève les + / -, et je fais les deux à part

**Comment by julesduroux** [comment]
Attention ! La couleur veut déjà dire que ça a marché ou échoué ! Ça ne
peut pas en plus dire que c'est positif ou négatif.

A moins qu'on mette une grosse croix sur le symbole pour dire que ça a
échoué ?

**Comment by Licoti** [comment]
Mais les icones ne doivent pas rester toujours en blanc normalement ?

**Comment by julesduroux** [comment]
Bonne question. Je crois qu'on en avait uniquement parlé avec Matthieu.

On a plusieurs informations a faire passer sur chaque symbole. Prenons
l'exemple d'une run d'extraction a afficher sur le marché d'une cirporation
qui est un des cas les plus complexe :
-si la run est passée ou pas
-s'il s'agit de la cible ou du bénéficiaire
-les infos méta : quel joueur a lancé la run, quel était le %de réussite,
etc...

On pourrait tout mettre dans les infos méta mais le joueur aurait alors à
passer la souris sur toutes les icônes. Je propose de l' aider un peu en
affichant des effets visuels en plus pour afficher les deux premières
informations. Si les effets positifs sont en vert et les effets négatifs
sont en rouge on sait si on est la cible ou le bénéficiaire de la run. Si
l'icône est barré on sait que le run a échoué.

En revanche sur le joueur on aura pas l'information de couleur pour une run
(parce qu'il n'est ni la cible ni le bénéficiaire) mais on aurait l'info
d'échec ou de réussite.

Attention, il y aurait quand même des informations en couleur sur un joueur
comme pour l'effet du MDC consolidation, il faudrait avoir l'info de
couleur sur le joueur pour savoir si l'effet lui a été positif ou négatif.

On pourrait aussi garder tous les icones en blanc et mettre des +/- dans
les logos.

Jules

**Comment by Licoti** [comment]
Du coup : nouvel essai avec des icones barrés

**Comment by Neamar** [comment]
Pas mal ! Par contre je ne comprends pas pourquoi on a 3 "DInc: Développement urbain", le positif et négatif devraient suffire non ?

**Comment by Licoti** [comment]
Aucune idée :o), je l'ai fait au cas où

**Comment by Neamar** [comment]
@Licoti il faudrait aussi une icone pour DInc "None", quand aucune ligne ne passe. J'avais souvenir d'en avoir vu une mais impossible de remettre la main dessus ?

**Comment by Neamar** [comment]
On continue sur #182 avec des svg :) je ferme ici !
