### ISSUE TITLE
Order Page

### ISSUE THREAD

**Issue by Licoti** [Neamar/corporate#129]
![corporate-v2-ordre](https://cloud.githubusercontent.com/assets/539146/7431661/00433d6e-f021-11e4-8984-45b4947e1601.jpg)

**Comment by Neamar** [comment]
Ça claaaque :)

Quelques remarques quand même :

* Je n'afficherai pas le graphique Wallstreet ici
* Je n'afficherai pas la liste des tours ici
* Je mettrais les coûts avec des "k" (genre "5k" plutôt que "5000")
* Je mettrais le petit hachuré jaune sur les ordres que tu ne peux plus passer ce tour-ci (pas assez d'argent, déjà fait, pas de cible, etc)

**Comment by your-mom-noob** [comment]
Tant qu'à faire, autant mettre le petit hachuré en rouge, si c'est pour dire que tu ne peux pas le faire

**Comment by Licoti** [comment]
Pour le bouton en rouge :
![rouge-bouton](https://cloud.githubusercontent.com/assets/539146/7431937/c04d8572-f023-11e4-991b-8737a8985748.png)

**Comment by Licoti** [comment]
![corporate-v2-ordre](https://cloud.githubusercontent.com/assets/539146/7432620/fa6e38b8-f029-11e4-84ed-5b55c1a7fa37.jpg)
