### ISSUE TITLE
Main template layout

### ISSUE THREAD

**Issue by Neamar** [Neamar/corporate#132]

**Comment by Licoti** [comment]
![corporate-v3-layout](https://cloud.githubusercontent.com/assets/539146/7433598/5b73e65e-f033-11e4-93c2-2b9b956841ac.jpg)

**Comment by Licoti** [comment]
![corporate-v3-layout](https://cloud.githubusercontent.com/assets/539146/7433722/73be18a0-f034-11e4-8dde-0b2e9075f7a1.jpg)

**Comment by Licoti** [comment]
![corporate-v3 1](https://cloud.githubusercontent.com/assets/539146/7440749/8d1bb4d2-f0c6-11e4-9ab5-47f5deef785b.jpg)

**Comment by Licoti** [comment]
![corporate-v3 1-gloabal](https://cloud.githubusercontent.com/assets/539146/7441196/2c1f3124-f0dd-11e4-862e-382323e77ff5.jpg)
