### ISSUE TITLE
Player detail page

### ISSUE THREAD

**Issue by Neamar** [Neamar/corporate#133]
Pour le joueur, on affiche :

* Son nom
* Son avatar
* La ligne DInc qu'il a voté ce tour-ci
* Le nombre de voix qu'il a au DInc
* Le nombre de parts possédées
* Ses parts par corpo
* Nationalité corpo
* Son IC
* Ses dividendes
* Les actions connues

**Comment by Licoti** [comment]
![corporate-v3-player](https://cloud.githubusercontent.com/assets/539146/7438832/7d97678c-f06b-11e4-984f-bf5f74ba0014.jpg)

**Comment by Licoti** [comment]
![corporate-v3-player](https://cloud.githubusercontent.com/assets/539146/7440598/3a7773da-f0bf-11e4-81e2-4429952f997e.jpg)

**Comment by Licoti** [comment]
![corporate-v3-player](https://cloud.githubusercontent.com/assets/539146/7440646/b268c7b6-f0c1-11e4-92da-a2b58ee5483a.jpg)

**Comment by HK-Seb** [comment]
Est ce normal que la citoyenneté corporatiste n'apparaissent pas ?

**Comment by Neamar** [comment]
Hum, bonne remarque. Je crois qu'on avait prévu de jouer sur les "parts" du joueur (par exemple un liseré doré si c'est la corpo dont tu es citoyen)
