### ISSUE TITLE
Nom de la corporation Agroalimentaire

### ISSUE THREAD

**Issue by Neamar** [Neamar/corporate#156]
La discussion fait toujours rage sur #114.

Les premières propositions étaient sur https://github.com/Neamar/corporate/pull/114#discussion-diff-27103662 mais aucune n'était satisfaisantes, on relance un round de discussion from scratch ?

**Comment by HK-Seb** [comment]
Je propose de ne trouver que des idées nouvelles et de comparer les meilleures alternatives aux options retenues précédemment.

Je rappelle le texte actuelle pour l'ambiance de la corpo, **lui aussi sujet à modification au besoin** !

"Issu des magnats du riz en Asie du Sud-Est et du soja au Brésil, X est une entreprise à l’image presque idéale. Dôtée d'une énergie presque végétale, elle est opportuniste et surfe sur une nouvelle vague de l’alimentation bio et de l’énergie renouvelable. Médecine préventive, réseaux de transports collaboratifs, satellites de focalisation solaire et agriculture biologique, X promet tout simplement une vie plus saine, plus proche de la nature, s’impliquant notamment dans de nombreuses organisations de défenses.

Si l’on parvient à voir au-delà de cette image (qu’elle soigne néanmoins avec une attention particulière), on voit rapidement que X est une corporation tout ce qu'il y a de plus carnivore et prédatrice usant de moyens détournés pour arriver à ses fins sans détériorer son image publique. Par l’intermédiaire de coopératives agricoles, de groupes éco terroristes ou d’associations de soutien aux malades, X possède un réseau à sa disposition d’agents désespérés, déterminés et protéiformes qui font avancer ses intérêts à moindre coût.

Peu savent à quel point les racines de cette corporation s’étendent, mais une chose est sûre : X rayonne maintenant mondialement."

Et le texte des Operatives (Runners)

"T’as la fibre écolo petit ?

Tu t’entendras à merveille ces mecs-là. Leurs potes les appellent écoresponsable proactifs, je les appelle écoterroristes extrémistes imposant la dictature du bien-pensant. Ces mecs ont rien à perdre. Leur unité de prod’ de base, c’est le pauvre ravagé par les épidémies et les bouleversements climatiques. Ils nourrissent la planète et t’as juste pas envie de les avoir à dos.

Avec Bastion, ils s’envoient de ces raclées ! Tu te souviens de ce massacre au Ghana… Ben ouais, X qui se lance contre un gouvernement de Bastion. Le coup d’état militaire en Indonésie ? Bastion qui renverse X. Les plantes vertes n’acceptent que les plus cinglés pour bosser pour eux. Les désespérés, les malades… Ils peuvent faire des alliés aussi imposants que le poids de leurs convictions… Donc ne les sous-estime pas quand ils sont en face. Alors oui, c’est un pouilleux mal fringué… Mais il n’a rien à perdre et sa ceinture d’explosif fera facilement péter ta raffinerie…

Par contre, il faut reconnaître que la bouffe qu’ils font n’est pas dégueulasse…"

Je lance donc la première salve, l'idée de cette corporation est d'être en opposition en termes de BG avec Bastion, très "américaine" dans son approche, quitte à changer un peu le BG. Dans cette idée :
* Shennong (clivage Chine US)
* Tlaloc (clivage Amérique Nord/Sud)
* Kamaq (clivage Amérique Nord/Sud)
* Sorgho (clivage Nord Sud)
* Entelechy (http://fr.wiktionary.org/wiki/ent%C3%A9l%C3%A9chie clivage spirituel/matériel)

Je rappelle mon affection toute particulière pour les noms composés. Toutes mes suggestions X peuvent être combinées sous forme
Consortium X
X Technologies
X Enterprises

Qu'en pensez vous ?

**Comment by Neamar** [comment]
J'aime bien Tlaloc. Ça sonne bien, c'est en rapport (déesse de la pluie aztèque) et assez exotique.

(pour info annexe : dans Shadowrun, Tlaloc est un satellite de recherche militaire / biological warfare pour Aztechnoly. Pas vraiment la même chose !)

Pas forcément fan d'y ajouter un "Consortium" derrière.

**Comment by Neamar** [comment]
(ping @your-mom-noob @Izou et @Licoti, si vous avez une opinion ?)

**Comment by HK-Seb** [comment]
L'idée d'avoir un nom composé était de pouvoir jouer sur une divinité comme Kamaq ou Tlaloc sans pour autant avoir la même typologie que Mercury, (aussi une divinité). Ca peut déranger et avoir un composé était un moyen d'éviter la ressemblance, et je reconnais que j'aime la sonorité Consortium Tlaloc, qui est bien distinct des noms actuels.

**Comment by Neamar** [comment]
Du coup @julesduroux vote blanc, et @your-mom-noob dit "qu'il kiffe tlaloc".

On part là dessus donc !

**Comment by HK-Seb** [comment]
Avec ou sans Consortium ?

**Comment by Neamar** [comment]
Perso je suis plus sur Tlaloc tout court ;)

**Comment by HK-Seb** [comment]
Je n'insiste pas, bon si quelqu'un a quelque chose contre Tlaloc, qu'il parle maintenant ou se taise à jamais :)

**Comment by Neamar** [comment]
Ok, du coup j'ai modifié #114 pour renommer Àdéfinir en Tlaloc.

Je merge #114 on en fera une nouvelle pour les effets premiers derniers ;)
