### ISSUE TITLE
Effets premiers / derniers / crash

### ISSUE THREAD

**Issue by Neamar** [Neamar/corporate#157]
Hello,

Cf. #119 pour les détails techniques.

Dans l'état actuel, voici ce qu'on propose avec @HK-Seb pour les effets.

## Effets premiers
![first](https://cloud.githubusercontent.com/assets/536844/7723309/f540aa02-fee7-11e4-9dea-685f69d91815.png)

## Effets derniers
![last](https://cloud.githubusercontent.com/assets/536844/7723316/fd88d5c2-fee7-11e4-83f4-6aab326327e3.png)

## Effets crash
![crash](https://cloud.githubusercontent.com/assets/536844/7723321/032a427c-fee8-11e4-9d5b-1444e8e591f1.png)

Ouvert à tous vos retours ;)

**Comment by HK-Seb** [comment]
Une fois ces effets finalisés, je pourrais passer à la rédaction des phrases d'explications !

**Comment by Neamar** [comment]
@your-mom-noob , @julesduroux une réaction ?

**Comment by HK-Seb** [comment]
Un petit résumé de ma discussion avec @julesduroux 

Globalement, Jules formule deux suggestions correctives

1. Des effets crash moins ciblé. La double flèche devrait être un maximum. On citera un exemple ou un joueur de Bastion n'a pas d'opposition chez Pemmican, et écraser pour se choper plus un par tour voir plus 4 en fin de game. L'idée de Jules : ne plus savoir qui est en position de force de par ses effets hautement volatile, c'est un peu dommage.

2. Trop de flèches s'orientent vers des positions. Selon Jules, d'estimer d'évaluer l'importance de négatif sur le second ou l'avant dernier, ou même sur le premier ou dernier. Pour les effets premiers, on a 8 flèche sur 20 qui sont intercorpo et 7 sur 20 pour les effets derniers. Conclusion, peu d'interdépendance. En multipliant les interdépendance, on peut plus facilement créer des camps, des oppositions. On a un duo fort, un duo faible et un trio... Peut être faudrait il créer un troisième trio avec Enercore, Taurus et Mercury.

Que pensez vous des remarques de Jules :)  ?

**Comment by Neamar** [comment]
Une corpo qio crashe ne génère pas son effet dernier, juste le crash.

De façon plus générique même, si une quelconque corpo crashe, il n'y a pas d'effets dernier ce tour ci, uniquement un ou plusieurs effets crash.

Peut-être à clarifier dans les règles ?

**Comment by Neamar** [comment]
Pour les remarques de @julesduroux , la double flèche me semble faible pour un crash. Ne pas toutes les mettre en *4, ok, mais en conserver quelques unes me semble intéressant tout de même.

**Comment by HK-Seb** [comment]
![image](https://cloud.githubusercontent.com/assets/11852952/8030807/213ff626-0dca-11e5-9f54-4aceceeeb069.png)

**Comment by Neamar** [comment]
Je ne suis pas un spécialiste, et j'apprécie le boulot effectué (même si je préfère mes graphiques :D) mais je trouve intéressant d'avoir le second au moins -- ça permet de jouer différemment et de déséquilibrer les statu quo.

Pour l'avant dernier, j'imagine qu'on peut effectivement s'en passer

**Comment by HK-Seb** [comment]
![image](https://cloud.githubusercontent.com/assets/11852952/8081890/090b5b6c-0f79-11e5-96ec-c5bf8df0ed62.png)

Version 3

Changement : ajout d'une colonne second, diminution de la dispersion dans les effets Crash, diminution des interactions dans le bloc "corpos du quotidien"

Mécaniques à remarquer (ou non) que j'ai inséré, n'hésitez pas à formuler des objections
Aucun effet crash n'affecte Enercore
Aucun effet premier dernier n'affecte Iris
Le total des effets Crash est de 0 cad en moyenne, un crash est neutre pour l'économie des survivants
Iris et CityGroup ont un lien avec Taurus
CityGroup a un effet dernier stabilisant (sautoboost) mais un effet premier qui force la concurrence (+1 au second)

Quelle version préféré vous ?
Préférez vous la forme diagramme ?

**Comment by HK-Seb** [comment]
Peut être peux t'on procéder de cette façon, si vous n'avez pas de suggestions, on peut tester comme ça et voir comment ça tourne !

Si l'un d'entre vous présente une quelconque opposition à ce tableau, qu'il parle maintenant ou se taise à jamais !

**Comment by HK-Seb** [comment]
Effets premiers

![image](https://cloud.githubusercontent.com/assets/11852952/8328884/e38ec64c-1a74-11e5-9cd6-9a1d8b200cf3.png)

Effets derniers

![image](https://cloud.githubusercontent.com/assets/11852952/8328951/aa1e8d38-1a75-11e5-8429-edb3bab84c6e.png)

Effet crash (les bleus sont des triples vertes, les noires des triples rouges)

![image](https://cloud.githubusercontent.com/assets/11852952/8329229/fb41eb7c-1a77-11e5-8bbc-8cbf9453f8a6.png)

**Comment by Neamar** [comment]
@julesduroux une opinion?

**Comment by Neamar** [comment]
Perso ça me semble viable et ça fait des jolis graphiques ;)

(ça fait tellement mal au premier quand Mercury crashe ><)

**Comment by HK-Seb** [comment]
Nous voulions la dynamique avec Mercury... Son effet dernier rapportant +2 au premier (ce qui est quand même gros), je pense que nous sommes relativement équilibré.
Le seul moyen malheureusement, c'est de tester !

**Comment by HK-Seb** [comment]
Et un premier lancer pour les effets premier dernier et crash


Effet Premier : 
Bastion : Profitant de sa position de premier, Bastion capitalise pour étendre sa vision du monde et renforcer ses positions. Tlaloc et ses alliés reculent face à la pression ultra moderniste.
Tlaloc : En position de meneur, Tlaloc provoque un changement important dans l'économie mondiale, la tournant à son avantage en pressurisant la création de nouvelles normes environnementales et sociales plus strictes ayant un gros impact sur Bastion.
Mercury : La jeune méga corpo raffole de sa position et se souvient de ses origines. Elle signe des partenariats mutuellement profitables avec les plus petits et consolide son association avec EnerCore.
EnerCore : L'énergie est disponible pour tous alors EnerCore s'élève en haut de la pyramide. Cette opportunité est saisie par les plus grands acteurs du marché qui ont la possibilité de capitaliser sur le phénomène, ainsi que le domaine des transports qui électrique, une spécialité Taurus Industries.
Taurus Industries : Retrouvant sa place historique, Taurus Industries a tous les outils en main pour appliquer sa stratégie prédatrice sur ses concurrents directs et pour tenter d'affaiblir la position d'EnerCore afin de mettre la main sur leurs BlackSuns.
Pure : Les filiales de Pure se démultiplient, offrant aux hommes une version du monde où le transhumain remplace les machines. Le marché des ADAI de Shinsekai connait un ralentissement tandis qu'Impulse profite de cet engouement technologique pour développer son projet Mars.
Shinsekai : La corporation japonaise profite de sa position de leader pour inonder le marché d'ADAI servant au quotidien. De nombreuses filiales de Pure doivent être restructurées tandis qu'Impulse fait avancer son programme de conquête martienne.
Impulse : La méga corporation B2B peut maintenant offrir directement au consommateur des produits de haute technologie particulièrement innovant et performant. Les produits Shinsekai et Pure prennent un coup de vieux et connaissent une baisse de rentabilité.
Iris : Iris devient un modèle de la réussite des réseaux et use de sa position de force pour enfoncer les entreprises en difficulté à coup de scandale médiatiques. CityGroup profite de cet engouement, les masses hypnotisées affluant en masse vers les villes pour vivre le rêve d’Iris.
CityGroup : CityGroup surfe sur son avantage concurrentiel pour créer des infrastructures et trouver de nouveaux alliés puissants. De plus, elle impose une guerre des prix, empêchant les corporations en difficulté de remonter la pente.


Effet Dernier : 
Bastion : Au fond du trou, les investisseurs de Bastion quittent le navire. Sa vision s'effrite avec ses actifs, profitant à Tlaloc et sa philosophie New Age.
Tlaloc : Sa voix faiblissant en impact sur la scène corporatiste, Tlaloc perd rapidement la confiance d'alliés précieux, qui enlèvent autant d'épines dans le pied de Bastion.
Mercury : Son innovation légendaire connaissant un ralentissement important, Mercury se voit obligé de réaliser des contrats juteux de mercenariat de cyberguerre au plus offrant afin de garder la tête hors de l'eau.
EnerCore : Sa puissance financière diminuant, la supériorité technologique d'EnerCore laisse place à de nouveaux acteurs dont les performances ne sont plus à prouver. Shinsekai et Pure, les méga corporations les plus agressives technologiquement, s’engouffrent dans la brèche.
Taurus Industries : Afin d'éviter la saignée, Taurus Industries coupe les lignes de transport les moins rentables, rendant les déplacements et donc les affrontements au travers le monde plus complexe. Cette situation nuit directement à Bastion et à Tlaloc, dont le succès et l’image sont directement dépendants de ces campagnes.
Pure : Avec plusieurs filiales en difficulté financière, Pure cède du terrain à Shinsekai sur le marché des produits de luxe. Afin de limiter les coûts, elle se débarrasse de ses prestataires Impulse.
Shinsekai : Avec une abnégation toute japonaise, Shinsekai vends plusieurs actifs à Pure tout en réduisant ses effectifs de consultants afin d'améliorer sa rentabilité.
Impulse : En difficulté financière, la corporation met en place des algorithmes financiers complexes causant la baisse de l'acteur le plus important du marché. Impulse est de plus contraint à mettre en pause son partenariat avec CityGroup sur le projet Mars.
Iris : Iris perdant pied, elle tente de relancer l'audimat en usant de dossier, causant du tort à la corporation avec le plus de squelette au placard : Taurus Industries. Le déluge d'information devant être régulé, Mercury et ses programmes de défenses deviennent très populaires.
CityGroup : Fier de son aptitude à trouver de bonnes opportunités même dans les situations les plus désespérées, CityGroup trouve le moyen de regagner un second souffle. Néanmoins, l'infrastructure des villes diminuant, les options de transport en souffre autant, imposant un ralentissement à Taurus Industries.


Effet Crash : 
Bastion : Bastion perd définitivement le pari de l'interventionnisme. Sa chute propulse Tlaloc vers l'avant ainsi que Taurus Industries qui s'impose comme la nouvelle norme militaire. De nombreux projets militaires Impulse destinés au projet Mars sont abandonnés. Les meilleurs actifs de Bastion sont vendus au plus offrant.
Tlaloc : Tlaloc perds le masque de la bienséance, donnant raison à Bastion et sa vision manichéenne et ultramoderne. Impulse profite de ce retour du monde à la foi dans le progrès technique tandis que Pure et CityGroup perdent leur principal fournisseur en produit naturel, créant une baisse de rentabilité.
Mercury : Le rêve d'Alan s'effondre, mais dans un sursaut de folie, il décide de ne pas chuter seul. Coordonnant une ultime attaque cybernétique, il paralyse et endommage les puissants.
EnerCore : Face à la banqueroute, EnerCore n'a d'autres choix que vendre le secret du BlackSuns à Iris et ses parts de Mercury au rabais. La chute de la corporation provoque une montée des prix de l'énergie et donc une recherche vers des logements plus isolante et performante que le bio béton de CityGroup.
Taurus Industries : Taurus Industries ne chute jamais. Alors que les investisseurs pensent l'abandonner, son directeur lance une nouvelle campagne de réduction des coûts et d'innovation si convaincante et efficace qu'elle revient dans la course.
Pure : Pure chute, provoquant la baisse des produits de luxe et la priorité n'est plus au paraitre. Iris souffre de cette dépréciation de l'image tandis que CityGroup ramène aux valeurs de bases. Le vide de marché causé par la chute de ses multiples filiales présente une opportunité pour les étoiles montantes.
Shinsekai : Quittant la scène internationale, Shinsekaï limite ses pertes en vendant à prix cassés des ADAI aux belligérants du conflit Tlaloc/Bastion. Elle rapatrie de plus de nombreuses ADAI de gestion en leasing chez les plus puissants.
Impulse : Vendant son projet Mars au plus offrant, Impulse est dissolue. Son savoir-faire commun est disséminé, causant notamment des dysfonctionnements dans le QG d’Iris. Mercury perd son principal client en termes de programme de défense informatique.
Iris : Iris chute, laissant un vide important dans de nombreux marchés profitant notamment à de nombreuses filiales de Pure. Impulse met la main sur le QG tandis que les masses, moins hypnotisés par les programmes Iris, aspire à mieux pour eux même que le bio béton CityGroup.
CityGroup : CityGroup chute et ses infrastructures s’effondrent. Taurus Industries souffre particulièrement, ses transports n'étant plus aussi bien managés. Iris réalise une campagne de médiatisation mettant en scène la chute de CityGroup comme la mort d'un héros populaire, faisant grimper l'audimat.

**Comment by Neamar** [comment]
Pour info, j'ai fermé #119 pour la remplacer par #159 qui merge directement dans #99.

**Comment by Neamar** [comment]
Du coup @HK-Seb peux-tu ajouter tes descriptions sur les fichiers des corpos ? Ça permettra de mettre les commentaires en direct.

Tu peux faire ça depuis cette URL : https://github.com/Neamar/corporate/tree/v2-firstlast/data/cities/detroit/corporations en modifiant les corporations.
J'ai fait Bastion en exemple : https://github.com/Neamar/corporate/commit/4fcc9e976b68018133bf4017c0a80598bdfd5014

**Comment by HK-Seb** [comment]
@Neamar C'est fait, petit bug d'affichage sur l'effet crash de tlaloc si tu veux y jeter un oeil

**Comment by Neamar** [comment]
Indeed, le bug sur Tlaloc m'a rendu à moitié fou quand je l'ai vu et j'ai mis longtemps à le trouver : https://github.com/Neamar/corporate/commit/8311be1bd1a9ba2f13c47f52bb11ea862793946e

Du coup maintenant je vais relire tout ça sur la PR et mettre des commentaires en direct, merci !

**Comment by Neamar** [comment]
PRs mergées, j'ai mis un bout d'implémentation aussi.

Je pense qu'il faudra revenir pour voir quels marchés sont affectés, mais on verra ça plus tard ;)
