### ISSUE TITLE
Icons name list

### ISSUE THREAD

**Issue by Neamar** [Neamar/corporate#182]
See: https://github.com/Neamar/corporate/tree/1f2f5e7a3df191ec9ee6b4594b49b2e8fc59f8a1/website/static/img/logs
And: https://github.com/Neamar/corporate/tree/1f2f5e7a3df191ec9ee6b4594b49b2e8fc59f8a1/website/static/img/market

## LOGS

* [x] voice_up
* [x] voice_down
* [x] first_effect
* [x] last_effect
* [x] crash_effect
* [x] ope_sabotage
* [x] ope_sabotage_fail (barré)
* [x] ope_datasteal_up (green)
* [x] ope_datasteal_fail_up (barré, green)
* [x] ope_datasteal_fail_down (barré, red)
* [x] ope_datasteal_down (red)
* [x] ope_protection
* [x] ope_extraction_up (green)
* [x] ope_extraction_fail_up (barré, green)
* [x] ope_extraction_fail_down (barré, red)
* [x] ope_extraction_down (red)
* [ ] effect_contrat_up (green)
* [ ] effect_contrat_down (red)
* [x] market_hand_up (green)
* [x] market_hand_down (red)
* [x] add_citizenship
* [x] remove_citizenship
* [x] ic_up
* [x] ope_information
* [ ] effect_consolidation_up (green)
* [ ] effect_consolidation_down (red)
* [ ] effect_security_up (green)
* [ ] effect_security_down (red)
* [x] speculation_win (green)
* [x] speculation_lost (red)
* [x] wiretransfer
* [x] buy_share
* [ ] vote_consolidation
* [ ] vote_security
* [ ] vote_contrat
* [x] money_next_turn
* [x] background
* [ ] gain_domination_bubble (green)
* [ ] lose_domination_bubble (red)
* [ ] gain_dry_bubble (red attention c'est inversé ;))
* [ ] lose_dry_bubble (green)

## ORDERS
- [x] voteorder
- [x] buyshareorder
- [ ] dincvoteorder
- [x] buyinfluenceorder
- [x] citizenshiporder
- [x] datastealorder
- [x] sabotageorder
- [x] extractionorder
- [x] informationorder
- [x] protectionorder
- [x] corporationspeculationorder
- [x] wiretransferorder

## MARKETS
- [x] alimentaire
- [x] btp
- [x] energy
- [x] media
- [x] medical
- [x] military
- [x] robot
- [x] space
- [x] telecom
- [x] transport

**Comment by Neamar** [comment]
@julesduroux tu peux ajouter la version "groupée" de tout ça ?

**Comment by julesduroux** [comment]
Voilà les logos regroupés
pour les logs :
voice_up : https://github.com/Neamar/corporate/blob/1f2f5e7a3df191ec9ee6b4594b49b2e8fc59f8a1/website/static/img/logs/voice_up.png?raw=true
 voice_down : https://github.com/Neamar/corporate/blob/1f2f5e7a3df191ec9ee6b4594b49b2e8fc59f8a1/website/static/img/logs/voice_down.png?raw=true
 first_effect : https://github.com/Neamar/corporate/blob/1f2f5e7a3df191ec9ee6b4594b49b2e8fc59f8a1/website/static/img/logs/first_effect.png?raw=true
 last_effect : https://github.com/Neamar/corporate/blob/1f2f5e7a3df191ec9ee6b4594b49b2e8fc59f8a1/website/static/img/logs/last_effect.png?raw=true
 crash_effect : https://github.com/Neamar/corporate/blob/1f2f5e7a3df191ec9ee6b4594b49b2e8fc59f8a1/website/static/img/logs/crash_effect.png?raw=true
 ope_sabotage : https://github.com/Neamar/corporate/blob/1f2f5e7a3df191ec9ee6b4594b49b2e8fc59f8a1/website/static/img/logs/ope_sabotage.png?raw=true
 ope_sabotage_fail (barré) : TODO : le même qu'au dessus mais barré
 ope_datasteal_up (green) : TODO : le même que l'url sans le + : https://github.com/Neamar/corporate/blob/1f2f5e7a3df191ec9ee6b4594b49b2e8fc59f8a1/website/static/img/logs/ope_datasteal_up.png?raw=true
 ope_datasteal_fail_up (barré, green) : TODO : le même que l'url  mais barré et sans le - : https://github.com/Neamar/corporate/blob/1f2f5e7a3df191ec9ee6b4594b49b2e8fc59f8a1/website/static/img/logs/ope_datasteal_down.png?raw=true
 ope_datasteal_fail_down (barré, red) : le même que ope_datasteal_up
 ope_datasteal_down (red) : le même que ope_datasetal_down
 ope_protection : https://github.com/Neamar/corporate/blob/1f2f5e7a3df191ec9ee6b4594b49b2e8fc59f8a1/website/static/img/logs/ope_protection.png?raw=true
 ope_extraction_up (green) : le même que ça mais sans le + : https://github.com/Neamar/corporate/blob/1f2f5e7a3df191ec9ee6b4594b49b2e8fc59f8a1/website/static/img/logs/ope_extraction_up.png?raw=true
 ope_extraction_fail_up (barré, green) : le même que ça mais sans le - et barré : https://github.com/Neamar/corporate/blob/1f2f5e7a3df191ec9ee6b4594b49b2e8fc59f8a1/website/static/img/logs/ope_extraction_down.png?raw=true
 ope_extraction_fail_down (barré, red) : le même que  ope_extraction_fail_up
 ope_extraction_down (red) : le même que  ope_extraction_up
 effect_contrat_up (green) : TODO : logo qui rappelle Dinc conrat public
 effect_contrat_down (red) : le même que effect_contrat_up
 market_hand_up (green) : TODO : icône de la main du marché. Tu l'a peut être déjà fait mais je ne l'ai pas vu
 market_hand_down (red) : le même que market_hand_up
 add_citizenship : https://github.com/Neamar/corporate/blob/1f2f5e7a3df191ec9ee6b4594b49b2e8fc59f8a1/website/static/img/logs/add_citizenship.png?raw=true
 remove_citizenship : https://github.com/Neamar/corporate/blob/1f2f5e7a3df191ec9ee6b4594b49b2e8fc59f8a1/website/static/img/logs/remove_citizenship.png?raw=true
 ic_up : https://github.com/Neamar/corporate/blob/1f2f5e7a3df191ec9ee6b4594b49b2e8fc59f8a1/website/static/img/logs/ic_up.png?raw=true
 ope_information : https://github.com/Neamar/corporate/blob/1f2f5e7a3df191ec9ee6b4594b49b2e8fc59f8a1/website/static/img/logs/ope_information.png?raw=true
 effect_consolidation_up (green) : TODO : logo qui rappelle Dinc consolidation (briques)
 effect_consolidation_down (red) : le même que effect_consolidation_up
 effect_security_up (green) : TODO : logo qui rappelle Dinc securité (étoile de shériff)
 effect_security_down (red) : le même que effect_security_up
 speculation_win (green) : existe : icône de spéculation
 speculation_lost (red) : existe : icône de spéculation
 wiretransfer : https://github.com/Neamar/corporate/blob/1f2f5e7a3df191ec9ee6b4594b49b2e8fc59f8a1/website/static/img/logs/wiretransfer.png?raw=true
 buy_share : https://github.com/Neamar/corporate/blob/1f2f5e7a3df191ec9ee6b4594b49b2e8fc59f8a1/website/static/img/logs/buy_share.png?raw=true
 vote_consolidation : le même que effect_consolidation_up
 vote_security : le même que effect_security_up
 vote_contrat : le même que effect_contrat_up
 money_next_turn : TODO : le problème c'est que le logo de l'argent ressemble beaucoup au logo d'achat de part. Il faudrait peut être prendre le logo de total de parts comme logo d'achat de part et récupérer le logo d'achat de part pour l'argent de fin de tour
 background : https://github.com/Neamar/corporate/blob/1f2f5e7a3df191ec9ee6b4594b49b2e8fc59f8a1/website/static/img/logs/background.png?raw=true
 gain_domination_bubble (green) : TODO
 lose_domination_bubble (red) : le même que gain_domination_bubble
 gain_dry_bubble (red attention c'est inversé ;)) : TODO
 lose_dry_bubble (green) : le même que gain_dry_bubble

pour les ordres :
 voteorder : le même que voice_up
 buyshareorder : le même que buy_share
 dincvoteorder : TODO : icône regroupant les 3 votes ?
 buyinfluenceorder : le même que ic_up
 citizenshiporder : le même que add_citizenship
 datastealorder : le même que ope_datasteal_up
 sabotageorder : le même que ope_sabotage
 extractionorder : le même que ope_extraction_up
 informationorder : lemême que ope_information
 protectionorder : le même que ope_protection
 corporationspeculationorder : le même que speculation
 wiretransferorder : le même que wiretransfer
et pour les marchéq je crois que tu as tour fait.

Plus que 11 ! Dont 5 qui sont des logos existants où il faut ajouter une croix ou retirer des +/-

**Comment by Licoti** [comment]
Pas compris pour celui-là :
https://cloud.githubusercontent.com/assets/539146/7889414/b7098eac-063f-11e5-81e2-0558ace3b3e5.png
 money_next_turn : TODO : le problème c'est que le logo de l'argent ressemble beaucoup au logo d'achat de part. Il faudrait peut être prendre le logo de total de parts comme logo d'achat de part et récupérer le logo d'achat de part pour l'argent de fin de tour
 background :

**Comment by julesduroux** [comment]
Désolé je n'avais pas associé ce logo à cette action. Mais maintenant que tu le dis c'est top :)

**Comment by Licoti** [comment]
Hello,

j'ai commencé à créer les icones. Ils sont répertoriées ici en SVG, il ne me reste que les dinc et les effets bulles.
on peut voir la puissance du SVG notamment sur les icones barrées où on peut mettre la croix d'une couleur différente pour plus de lisibilité si besoin. Dites moi s'il y a des choses à modifier.

https://github.com/Licoti/corporate-icon

**Comment by Neamar** [comment]
Hey @Licoti ! Je te conseille plutôt d'ouvrir directement une PR par ici et de les stocker dans le repo principal, comme ça on n'aura pas de soucis d'historique si un jour on veut remonter dans le temps.
