### ISSUE TITLE
Proofread effets premier dernier crash

### ISSUE THREAD

**Issue by Neamar** [Neamar/corporate#192]
Vérifier les effets premiers derniers (définis sur #159) et décider sur quels marchés ils doivent être appliqués.

@julesduroux / @HK-Seb ?

**Comment by HK-Seb** [comment]
Veux tu que je décide des marchés visés ? Ces + ou - ne sont ils pas
aléatoires ?

Le 2 août 2015 17:27, Matthieu Bacconnier <notifications@github.com> a
écrit :

**Comment by Neamar** [comment]
Il me semble qu'on avait prévu de les affecter directement à un marché lorsque c'était pertinent, aléatoire sinon.

**Comment by julesduroux** [comment]
Hello !

J'ai enfin pu me plonger en détail dans les effets prmier/dernier/crash (mieux vaut tard que jamais :P)
voici le lien : https://github.com/Neamar/corporate/issues/157

C'est vrai qu'on sent que ça a été réfléchi et que c'est abouti. On tient quelque chose de bien.

J'ai quelques ajustements de dernière minute tout de même que je vais argumenter : 
* Iris : -1 sur Pure au lieu de la dernière : Le mec qui est dernier et qui essaye de sauver sa corpo a autre chose à faire que de passer ses ressources à détrôner le premier pour qu'il arrête de le faire chier avec son -1 à chaque tour. Je ne suis pas contre le fait que ça existe, mais que ça existe deux fois je pense que c'est too much.
* Enercore : +1 sur CityGroup au lieu de la seconde. Mettre un +1 à la deuxième c'est comme dire que cette corpo ne sera jamais première.
Petit exemple pratique : la corpo A a 10 actif au tour 1, et la corpo B a 9 actifs. au tour 2, la corpo B passe à 11 et la corpo A à 10. Arrive les effets et du coup la corpo A remonte à 11. Comme il y a ex-aequo on reprend par rapport au tour d'avant et la corpo A reste en tête. 
Encore une fois je n'ai rien contre que ça existe, mais deux fois c'est trop.
* Taurus : -1 sur Shinsekai au lieu d'Enercore pour équilibrer les malus avec Pure et parce que Enercore n'est pas non plus une bête de course.
Après ça j'ai fait une petite analyse des corpos qui s'en sortaient bien sur les effets premier/derniers : 
Shinsekai, Tlaloc, Bastion et Pure s'en sortent très bien. Elles n'ont presque que des effets derniers qui leur font gagner des points et leurs effets premiers sont un bonus en soi. Donc si tu veux parier sur un champion, c'est une de ces quatre là. Certes les effets premiers ne sont peut être pas géniaux, mais si tu es premier c'est la fête. Ce qui tombe bien puisque tu vises justement la première place :)
En revanche Impulse, Taurus,Enercore et CityGroup sont plutôt des corpos qui ont du mal à monter en haut. Les effets derniers sont plutôt contre elles ou leurs effets premiers ne les arrangent pas trop. Mais en général ça compense par des effets premiersqui les arrangent ou des effets spéciaux qui font qu'elles sont dures à détruire. Elles sont donc un bon investissement économique.
Et c'est parfait comme ça ! Il faut qu'il y ait de la diversité et les inégalités sont assez bien dosées. Pourquoi cette analyse alors ? Pour les effets crash. Pour voir des retournements de situation sympatiques, on s'attend à avoir des effets crash qui visent les 4 corpos favories dans les sondages. Et bien non :(. Grosse décéption puisque Tlaloc et Bastion ne peuvent avoir que des bonus, Shinsekai n'a pas de bonus mais pas de malus non plus et Pure peut avoir des bonus comme des malus.

Histoire de ne pas tout remettre en cause non plus, je propose au moins les changements suivants : 
* Enercore : -2 sur Bastion au lieu de CityGroup
* CityGroup : -2 sur Tlaloc au lieu de Taurus
* Impulse : -2 sur Shinsekai au lieu de Iris

Pour en revenir au fil de discussion initial, les effets premier/dernier/crash s'appliquent effectivement à des marchés. Ca permet de prévoir ce qu'il faut pour garder ses dominations et d'éviter les pertes sèches. C'est pertinent à chaque fois que l'on cible une corporation précise. Par contre c'est au hasard quand on cible une position. HK, à toi de jouer :)

Sinon une petite remarque, je ne suis pas fan des liens noirs et bleus. Je préfère voir plein de traits et c'est beaucoup plus intuitif.

**Comment by HK-Seb** [comment]
Bon...

Alors j'ai bien tout lu et je te remercie pour ces remarques. Je vais donc répondre point par point

Iris : le -1 se justifiait en termes de background. En termes de mécanique, avoir elle ou CityGroup au top permettait de générer des parties avec beaucoup de crash ce qui pouvait causer des variétés de parties plus sympa. Soyons prédateurs God Dammit !

Enercore : J'aimais bien l'idée de la corpo "sympa". Bien sur, donner +1 à la seconde est un risque pour affirmer son hégémonie, mais je trouve justement que cette dynamique est intéressante. Avoir un véritable intérêt à la garder dans la course, c'est très intéressant. De manière générale, nous avons déjà beaucoup de liens inter-corpos. Avoir des liens avec des positions me semblent créer des interactions intéressantes et alternatives. Bien sur, être premier avec Enercore c'est plus challenging en termes de points, mais il est aussi plus facile de se trouver des alliés pour monter. Je penses qu'il est dommage de supprimer cette mécanique.

Taurus Industries : A voir du coup selon ce que l'on change

Ensuite vient ton analyse des corpos. Comme tu l'as bien observé, certaines corporations sont plus volatiles (forte en 1ere place, faible en dernière) quand d'autres sont plus stables. C'est effectivement voulu. J'ai équilibré les +1 et -1 avec les effets crashs selon une règle complètement arbitraire. Un différentiel de 1 dans un effet premier dernier équivalait à 4 de crash. Ainsi, pour reprendre l'exemple de Tlaloc. Elle possède en effet premier un effet qui s'autoboost, mais un effet premier d'une autre corpo (bastion) qui la mine. Même chose en effet dernier avec, en plus, l'influence de Taurus. Ainsi, Tlaloc première doit surveiller la position de Taurus pour éviter les pertes. Pour compenser cet effet, les effets crash lui donne un total de +4. Et cela est justifié car ce sont les corpos qui ont le plus d'interactions et sont le plus en affrontement direct. 
De même Pure et Shinsekai n'ont pas de corpos à surveiller lorsqu'ils sont en première place (pas d'effet dernier les pénalisant), mais lorsqu'ils sont en dernières places, ils n'ont que des -1 dans les effets premiers. C'est donc un investissement risqué... De plus, comme pour tout premier, avoir Impulse en dernière place est toujours un risque.
Le fait que Shinsekai n'est pas d'effet crash l'affectant était volontaire. Etant une japanocorp, je voulais qu'lle soit relativement neutre lors des débats des puissants pour écraser ou non une corpo. On a déjà cette thématique avec Enercore mais je la trouvais intéressante.
Ce que je remarque par contre, et cela mérite peut être réflection, c'est Impulse. Elle est vraiment intéressante à garder au fond du trou pour tout le monde sauf le premier. Et si le premier sens qu'il ne peut pas la relever, il n'a qu'a la faire crasher pour gagner un bonus... C'est la dynamique inverse (bien que plus légère) de Mercury. Selon vous, cette dynamique est elle bien stabilisatrice pour Impulse (comme souhaité à la base) ?

Les changements que tu proposes ne respecteraient plus ma règle de calcul (que j'ai appliqué à tout le monde). Comme tu le dis, avoir des déséquilibre théoriques n'est pas gênant car, si le jeu est bien fait, c'est le plus malin qui l'emporte et pas simplement la bonne corpo. Je préfèrerais tester en état, voir si effectivement ces corpos à haut risque sont trop solide une fois en haut. Et c'est la que le dosage des runs sera à faire avec une précision chirurgicale. Un poil trop puissant, les places changeront trop ; pas assez et il n'y aura plus de surprise.

Pour l'attribution sur les marchés, très bien, je peux m'y mettre dès qu'on aura gravé dans le marbre (pour la version alpha) les effets premiers derniers :)

A votre disposition pour en discuter par téléphone !

**Comment by Neamar** [comment]
Ping @julesduroux
