### ISSUE TITLE
Images de présentation pour les corpos

### ISSUE THREAD

**Issue by HK-Seb** [Neamar/corporate#195]
Voici quelques propositions d'images libre de droit pour illustrer les corporations. Nous pouvons les modifier au besoin (utilisation de photoshop etc.)

Pour Mercury
![image](https://cloud.githubusercontent.com/assets/11852952/9034016/b3a3f6f6-39cc-11e5-9c07-e3011f95816d.png)

Pour Iris
![image](https://cloud.githubusercontent.com/assets/11852952/9034001/9db1ae60-39cc-11e5-84e2-4ca7b806752a.png)

Pour Tlaloc
![image](https://cloud.githubusercontent.com/assets/11852952/9034050/edb6d728-39cc-11e5-9817-ed895cf4023b.png)

Pour Bastion
![image](https://cloud.githubusercontent.com/assets/11852952/9033983/853ae9f0-39cc-11e5-9f65-1682fdc19079.png)

Pour Shinsekai
![image](https://cloud.githubusercontent.com/assets/11852952/9033997/964c4626-39cc-11e5-86b0-1bc27773795c.png)

Pour Impulse
![image](https://cloud.githubusercontent.com/assets/11852952/9034008/aca66de8-39cc-11e5-9c06-1c262240bd2f.png)

Pour Taurus Industries
![image](https://cloud.githubusercontent.com/assets/11852952/9033971/69652c22-39cc-11e5-82d9-64a7d3b69886.png)

Pour Pure
![image](https://cloud.githubusercontent.com/assets/11852952/9033979/7adc481e-39cc-11e5-92f1-bf5c2bcb82c0.png)

Pour EnerCore
![image](https://cloud.githubusercontent.com/assets/11852952/9034004/a4da20e6-39cc-11e5-9adf-c02e0a561eff.png)

Pour CityGroup
![image](https://cloud.githubusercontent.com/assets/11852952/9033973/714336aa-39cc-11e5-80b8-90533d9775d8.png)

**Comment by Neamar** [comment]
Hi!

Ça pixellise un peu, mais en même temps on ne les affichera pas à cette taille ;)

Il faut effectivement voir comment ça s'intègre en ligne ; par exemple sur https://corporate-game-pr-131.herokuapp.com/docs/corporations/tlaloc

Les marchés dont on pense se servir actuellement sont sur https://github.com/Neamar/corporate/tree/ea93f1f24d5e6dbbee8a421889c26ef79be41be3/website/static/img/markets

(cc @Licoti / @Izou pour la partie créative de l'équipe)

**Comment by julesduroux** [comment]
Images mises à jour 
![bastion](https://cloud.githubusercontent.com/assets/4954765/15553508/b9fd5b78-22bf-11e6-864e-278f2d1b76f6.png)
![citygroup](https://cloud.githubusercontent.com/assets/4954765/15553511/b9fe62a2-22bf-11e6-97cf-47dbc1a38028.png)
![enercore](https://cloud.githubusercontent.com/assets/4954765/15553512/b9fe7d96-22bf-11e6-85ea-38563c4d40eb.png)
![impulse](https://cloud.githubusercontent.com/assets/4954765/15553509/b9fdc180-22bf-11e6-8fff-bf42e028b419.png)
![iris](https://cloud.githubusercontent.com/assets/4954765/15553513/ba026b2c-22bf-11e6-8a87-9aa4b079a8f6.png)
![mercury](https://cloud.githubusercontent.com/assets/4954765/15553510/b9fe1c02-22bf-11e6-96e3-94ab68fafef8.png)
![pure](https://cloud.githubusercontent.com/assets/4954765/15553515/ba0f6fa2-22bf-11e6-8dd0-78f5d7003b66.png)
![shinsekai](https://cloud.githubusercontent.com/assets/4954765/15553514/ba0f5e86-22bf-11e6-9249-558a6324e81d.png)
![taurus](https://cloud.githubusercontent.com/assets/4954765/15553517/ba1275d0-22bf-11e6-82a2-4def517f4900.png)
![tlaloc](https://cloud.githubusercontent.com/assets/4954765/15553516/ba108d10-22bf-11e6-82f6-668d27bc3609.png)
