### ISSUE TITLE
Responsive : page Comment jouer

### ISSUE THREAD

**Issue by HK-Seb** [Neamar/corporate#198]
Est ce normal que la page "comment jouer" ne soit pas responsive (quand je baisse la largeur de la fenetre je n'ai pas de barre en bas pour décaler) ?

https://corporate-game-pr-131.herokuapp.com/docs/

Exemple

![image](https://cloud.githubusercontent.com/assets/11852952/9062906/6d7603fa-3ac5-11e5-92b0-1e773fb5d2c5.png)

Qui deviens 

![image](https://cloud.githubusercontent.com/assets/11852952/9062925/8726f944-3ac5-11e5-8fab-ad82e198c45e.png)

**Comment by Neamar** [comment]
On fera une stylesheet mobile plus tard
