### ISSUE TITLE
Crash Effect

### ISSUE THREAD

**Issue by julesduroux** [Neamar/corporate#199]
Aujourd'hui l'effet crash est résolu à la toute fin du tour. Ce qui ne correspond pas du tout à ce qui est écrit dans les règles.

Il faudrait remonter l'effet crash juste après l'effet premier et l'effet dernier. Là encore un problème se pose c'est que la corporation est supprimée en base de donnée au moment du crash. Donc les tâches qui s'exécutent après ne fonctionnent pas correctement (comme la spéculation).

Il faut donc mettre en place une suppression logique (ajouter un champ IsCrashed sur la corpo) et passer sur TOUTES les requêtes pour voir si elles doivent être filtrées ou non.

Ca va aussi permettre de ne pas perdre les corporations crashées sur les tours où elles n'avaient pas encore crashées. Et en allant un peu plus loin, je pense qu'il est préférable de voir les corpos crashées dans Wallstreet le tour où elles ont crashées, histoire que les joueurs voient tout ce qu'elles se sont prises dans les dents. Ce sera beaucoup plus clair. Qu'en pensez-vous ?

**Comment by Neamar** [comment]
alors, c'est clairement pas un petit changement loin de là.

Dans l'idée, on peut utiliser les managers Django https://docs.djangoproject.com/en/1.8/topics/db/managers/. On ajoute une propriété `crashed` sur le modèle des corporations, et ensuite le manager `objects` modifie le queryset de base (cf. https://docs.djangoproject.com/en/1.8/topics/db/managers/#modifying-initial-manager-querysets) pour `.filter(crashed=False)` et on ajoute un manager `all_objects` pour les cas plus spéciaux où l'on a besoin de la donnée.

Concernant ta proposition pour la page Wallstreet... ça va pas être du gâteau ><. On verra ce qu'on peut faire !
