### ISSUE TITLE
Le message du WireTransfer plante

### ISSUE THREAD

**Issue by julesduroux** [Neamar/corporate#234]
![image](https://cloud.githubusercontent.com/assets/4954765/11850922/67e08e4a-a430-11e5-8cc5-084cb1cfe94f.png)

**Comment by Neamar** [comment]
C'est `{% if ... %}` et pas `If` (la majuscule ;))

Tu peux modifier directement le template et ça devrait fonctionner

**Comment by julesduroux** [comment]
Fixed :)
